/// Reads the version from pubspec.yaml and writes it to lib/version.dart.
///
/// Run this whenever pubspec.yaml version changes:
///   dart run tool/generate_version.dart
import 'dart:io';

void main() {
  final pubspec = File('pubspec.yaml').readAsStringSync();
  final match = RegExp(
    r'^version:\s*(\S+)',
    multiLine: true,
  ).firstMatch(pubspec);

  if (match == null) {
    stderr.writeln('Could not find version in pubspec.yaml');
    exitCode = 1;
    return;
  }

  final version = match.group(1)!;
  final output =
      '''// Generated by tool/generate_version.dart — do not edit by hand.
// Run `dart run tool/generate_version.dart` after bumping pubspec.yaml.
const String packageVersion = '$version';
''';

  File('lib/version.dart').writeAsStringSync(output);
  stdout.writeln('lib/version.dart updated to $version');
}
